name: slicing_ui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Version and build number for the application
version: 1.0.0+1

# Flutter SDK environment version constraints
environment:
  sdk: ">=3.3.4 <4.0.0"

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lottie: ^3.1.3
  google_fonts: ^6.2.1
  get_cli: ^1.8.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Add assets folder for application resources
  assets:
    - assets/
    - assets/lottie/

  # Uncomment and configure the following for custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
