// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWpxquZNauaTo4sQvi3Yr2qOsbvQXBiVc',
    appId: '1:909434803178:web:5f24dad64a378952025893',
    messagingSenderId: '909434803178',
    projectId: 'todomotion-de5b5',
    authDomain: 'todomotion-de5b5.firebaseapp.com',
    storageBucket: 'todomotion-de5b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNePNV3-Jl8SsN7QeJS9GgFD2Gagk4_Ow',
    appId: '1:909434803178:android:d2f20cf148d7bd1d025893',
    messagingSenderId: '909434803178',
    projectId: 'todomotion-de5b5',
    storageBucket: 'todomotion-de5b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5s0SscRfckUcQl7BeAnfw-sbW_hfbh5c',
    appId: '1:909434803178:ios:1b155576a85140f6025893',
    messagingSenderId: '909434803178',
    projectId: 'todomotion-de5b5',
    storageBucket: 'todomotion-de5b5.firebasestorage.app',
    iosBundleId: 'com.san.todo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5s0SscRfckUcQl7BeAnfw-sbW_hfbh5c',
    appId: '1:909434803178:ios:1b155576a85140f6025893',
    messagingSenderId: '909434803178',
    projectId: 'todomotion-de5b5',
    storageBucket: 'todomotion-de5b5.firebasestorage.app',
    iosBundleId: 'com.san.todo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWpxquZNauaTo4sQvi3Yr2qOsbvQXBiVc',
    appId: '1:909434803178:web:9ad477ac625f4b17025893',
    messagingSenderId: '909434803178',
    projectId: 'todomotion-de5b5',
    authDomain: 'todomotion-de5b5.firebaseapp.com',
    storageBucket: 'todomotion-de5b5.firebasestorage.app',
  );
}
